name: "Create Installation Token"
description: "Generates a token for a GitHub App installation."

inputs:
  clientId:
    description: "The client ID of the app."
    required: true
  privateKey:
    description: "The private key of the app for signing the JWT."
    required: true
  account:
    description: "The account to get the installation token for."
    required: true

outputs:
  token:
    value: "${{ steps.get-installation-token.outputs.token }}"
    description: "The generated installation token."

runs:
  using: 'composite'
  steps:
    - name: Generate JWT Token
      id: get-installation-token
      shell: pwsh
      run: |
        Set-Location './.github/actions/create-installation-token'
        $JWT = ./New-JWT.ps1 -ClientId ${{ inputs.clientId }} -PrivateKey ${{ inputs.privateKey }}
        
        $Token = ./New-InstallationToken.ps1 -JWT $JWT -Account ${{ inputs.account }}

        Add-Content -Path $env:GITHUB_OUTPUT -Value "token=$Token"