name: "Comment on Issue"
description: "Comments on a GitHub issue."

inputs:
  token:
    description: "The token to use for comment, must have write access to issues."
    required: true
  issue_number:
    description: "The issue number to comment on."
    required: true
  body:
    description: "The body of the comment to post."
    required: true
  repository:
    description: "The repository to comment on, in the format 'owner/repo'."
    required: true

runs:
  using: 'composite'
  steps:
    # Comment on Issue step