name: "Comment on Issue"
description: "Comments on a GitHub issue."

inputs:
  token:
    description: "The token to use for comment, must have write access to issues."
    required: true
  issue_number:
    description: "The issue number to comment on."
    required: true
  body:
    description: "The body of the comment to post."
    required: true
  repository:
    description: "The repository to comment on, in the format 'owner/repo'."
    required: true

runs:
  using: 'composite'
  steps:
    - name: Comment on Issue
      shell: pwsh
      env:
        ACCESS_TOKEN: ${{ inputs.token }}
      run: |
        $Token = if ($env:ACCESS_TOKEN) { $env:ACCESS_TOKEN } else { $env:token }
        $Issue = ${{ inputs.issue_number }}
        $Repo = ${{ inputs.repository }}
        $Body = ${{ inputs.body }}
        ./.github/actions/comment-issue/New-IssueComment.ps1 -Token $Token -IssueNumber $Issue -Repository $Repo -Body $Body