name: Comment on New Issue

on:
  issues:
    types: [opened]

jobs:
  get-token:
    runs-on: ubuntu-latest
    outputs:
      token: ${{ steps.get-installation-token.outputs.token }}
    permissions:
      issues: write # To comment on issues
      contents: read # To checkout the repository
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Get Installation Token
        id: get-installation-token
        uses: ./.github/actions/create-installation-token
        with:
          clientId: ${{ secrets.GH_APP_CLIENT_ID }}
          privateKey: ${{ secrets.GH_APP_PRIVATE_KEY }}
          account: ${{ github.repository_owner }}

  comment:
    runs-on: ubuntu-latest
    needs:
      get-token
    steps:
      - uses: actions/checkout@v4
      
      - name: Comment on Issue
        uses: ./.github/actions/comment-issue
        with:
          token: ${{ needs.get-token.outputs.token }}
          issue_number: ${{ github.event.issue.number }}
          repository: ${{ github.repository }}
          body: |
            Thanks for opening this issue! :star:

            Have you heard of [PowerShell Conference Europe](https://psconf.eu)? It is a great place to discuss challenges and solutions for PowerShell and related technologies! :computer: