name: Comment on New Issue

on:
  issues:
    types: [opened]

jobs:
  get-token:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Get Installation Token
      # Create App

      - name: Comment on Issue
        uses: ./.github/actions/comment-issue
        with:
          token: ${{ secrets.GITHUB_TOKEN }} # Replace with installation token
          issue_number: ${{ github.event.issue.number }}
          repository: ${{ github.repository }}
          body: |
            Thanks for opening this issue! :star:

            Have you heard of [PowerShell Conference Europe](https://psconf.eu)? It is a great place to discuss challenges and solutions for PowerShell and related technologies! :computer: