name: Comment on New Issue

on:
  issues:
    types: [opened]

jobs:
  create-mirror-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Get Installation Token
        id: get-installation-token
        uses: ./.github/actions/create-installation-token
        with:
          clientId: ${{ secrets.GH_APP_CLIENT_ID }}
          privateKey: ${{ secrets.GH_APP_PRIVATE_KEY }}
          account: ${{ github.repository_owner }}

      # Invoke mirror event
      - name: Start Mirror Workflow in Private Repository
        shell: pwsh
        env:
          TOKEN: ${{ steps.get-installation-token.outputs.token }}
        run: |
          $Headers = @{
            Accept = "application/vnd.github+json"
            Authorization = "Bearer ${{ env.TOKEN }}"
          }
        
          $Body = @{
            event_type = "mirror"
            client_payload = @{
              source_repo = "${{ github.repository }}"
              issue_number = "${{ github.event.issue.number }}"
              issue_link = "${{ github.event.issue.html_url }}"
              issue_title = "${{ github.event.issue.title }}"
            }
          } | ConvertTo-Json
          
          $Params = @{
            Uri = "https://api.github.com/repos/${{ vars.MIRROR_REPO }}/dispatches"
            Headers = $Headers
            Method = 'Post'
            Body = $Body
            ContentType = 'application/json'
          }

          Invoke-RestMethod @Params